name: Build & Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Frontend on VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "🚀 Starting frontend deployment"

            cd /home/deployer/apps/ecommerce-module

            echo "📥 Pulling latest code"
            git reset --hard
            git pull origin main

            echo "🧹 Cleaning old Docker cache (important for Vite env)"
            docker builder prune -f

            echo "🐳 Rebuilding frontend image (NO CACHE)"
            docker compose build frontend --no-cache

            echo "🔄 Restarting frontend container"
            docker compose up -d frontend

            echo "🧪 Verifying environment inside container"
            docker compose exec frontend printenv | grep VITE || echo "⚠️ ENV not found"

            echo "🔄 Reloading Nginx"
            docker restart nginx-proxy

            echo "✅ Deployment completed successfully"
